 set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design] 

set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS18} [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0 5} [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports output_signal]
set_property PACKAGE_PIN R1 [get_ports {output_signal[31]}]
set_property PACKAGE_PIN P2 [get_ports {output_signal[30]}]
set_property PACKAGE_PIN P1 [get_ports {output_signal[29]}]
set_property PACKAGE_PIN N2 [get_ports {output_signal[28]}]
set_property PACKAGE_PIN M1 [get_ports {output_signal[27]}]
set_property PACKAGE_PIN M2 [get_ports {output_signal[26]}]
set_property PACKAGE_PIN L1 [get_ports {output_signal[25]}]
set_property PACKAGE_PIN J2 [get_ports {output_signal[24]}]
set_property PACKAGE_PIN G1 [get_ports {output_signal[23]}]
set_property PACKAGE_PIN E1 [get_ports {output_signal[22]}]
set_property PACKAGE_PIN D2 [get_ports {output_signal[21]}]
set_property PACKAGE_PIN A1 [get_ports {output_signal[20]}]
set_property PACKAGE_PIN L3 [get_ports {output_signal[19]}]
set_property PACKAGE_PIN G3 [get_ports {output_signal[18]}]
set_property PACKAGE_PIN K4 [get_ports {output_signal[17]}]
set_property PACKAGE_PIN G4 [get_ports {output_signal[16]}]
set_property PACKAGE_PIN K1 [get_ports {output_signal[15]}]
set_property PACKAGE_PIN J1 [get_ports {output_signal[14]}]
set_property PACKAGE_PIN H2 [get_ports {output_signal[13]}]
set_property PACKAGE_PIN G2 [get_ports {output_signal[12]}]
set_property PACKAGE_PIN F1 [get_ports {output_signal[11]}]
set_property PACKAGE_PIN E2 [get_ports {output_signal[10]}]
set_property PACKAGE_PIN D1 [get_ports {output_signal[9]}]
set_property PACKAGE_PIN B1 [get_ports {output_signal[8]}]
set_property PACKAGE_PIN B2 [get_ports {output_signal[7]}]
set_property PACKAGE_PIN N3 [get_ports {output_signal[6]}]
set_property PACKAGE_PIN M3 [get_ports {output_signal[5]}]
set_property PACKAGE_PIN K3 [get_ports {output_signal[4]}]
set_property PACKAGE_PIN H3 [get_ports {output_signal[3]}]
set_property PACKAGE_PIN N4 [get_ports {output_signal[2]}]
set_property PACKAGE_PIN L4 [get_ports {output_signal[1]}]
set_property PACKAGE_PIN J4 [get_ports {output_signal[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports mclk]       
set_property PACKAGE_PIN R4 [get_ports mclk]   
set_property IOSTANDARD LVCMOS18 [get_ports rst]       
set_property PACKAGE_PIN AA4 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports Write_Reg]       
set_property PACKAGE_PIN AB6 [get_ports Write_Reg]            
set_property IOSTANDARD LVCMOS18 [get_ports sw_F_ZFOF]               
set_property PACKAGE_PIN V9 [get_ports sw_F_ZFOF]              


#ÊýÂë¹Ü
set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports which]
set_property PACKAGE_PIN N22 [get_ports {which[0]}]
set_property PACKAGE_PIN M21 [get_ports {which[1]}]
set_property PACKAGE_PIN M22 [get_ports {which[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN L21} [get_ports enable]


set_property SEVERITY {Warning} [get_drc_checks UCIO-1]