# LEDÒý½ÅÔ¼Êø (1-32)
set_property IOSTANDARD LVCMOS18 [get_ports PC_new]
set_property PACKAGE_PIN R1 [get_ports {PC_new[31]}]
set_property PACKAGE_PIN P2 [get_ports {PC_new[30]}]
set_property PACKAGE_PIN P1 [get_ports {PC_new[29]}]
set_property PACKAGE_PIN N2 [get_ports {PC_new[28]}]
set_property PACKAGE_PIN M1 [get_ports {PC_new[27]}]
set_property PACKAGE_PIN M2 [get_ports {PC_new[26]}]
set_property PACKAGE_PIN L1 [get_ports {PC_new[25]}]
set_property PACKAGE_PIN J2 [get_ports {PC_new[24]}]
set_property PACKAGE_PIN G1 [get_ports {PC_new[23]}]
set_property PACKAGE_PIN E1 [get_ports {PC_new[22]}]
set_property PACKAGE_PIN D2 [get_ports {PC_new[21]}]
set_property PACKAGE_PIN A1 [get_ports {PC_new[20]}]
set_property PACKAGE_PIN L3 [get_ports {PC_new[19]}]
set_property PACKAGE_PIN G3 [get_ports {PC_new[18]}]
set_property PACKAGE_PIN K4 [get_ports {PC_new[17]}]
set_property PACKAGE_PIN G4 [get_ports {PC_new[16]}]
set_property PACKAGE_PIN K1 [get_ports {PC_new[15]}]
set_property PACKAGE_PIN J1 [get_ports {PC_new[14]}]
set_property PACKAGE_PIN H2 [get_ports {PC_new[13]}]
set_property PACKAGE_PIN G2 [get_ports {PC_new[12]}]
set_property PACKAGE_PIN F1 [get_ports {PC_new[11]}]
set_property PACKAGE_PIN E2 [get_ports {PC_new[10]}]
set_property PACKAGE_PIN D1 [get_ports {PC_new[9]}]
set_property PACKAGE_PIN B1 [get_ports {PC_new[8]}]
set_property PACKAGE_PIN B2 [get_ports {PC_new[7]}]
set_property PACKAGE_PIN N3 [get_ports {PC_new[6]}]
set_property PACKAGE_PIN M3 [get_ports {PC_new[5]}]
set_property PACKAGE_PIN K3 [get_ports {PC_new[4]}]
set_property PACKAGE_PIN H3 [get_ports {PC_new[3]}]
set_property PACKAGE_PIN N4 [get_ports {PC_new[2]}]
set_property PACKAGE_PIN L4 [get_ports {PC_new[1]}]
set_property PACKAGE_PIN J4 [get_ports {PC_new[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property PACKAGE_PIN R4 [get_ports rst]

set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports which]
set_property PACKAGE_PIN N22 [get_ports {which[0]}]
set_property PACKAGE_PIN M21 [get_ports {which[1]}]
set_property PACKAGE_PIN M22 [get_ports {which[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN L21} [get_ports enable]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN H4} [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]   
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[1]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[2]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[3]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[4]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[5]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[6]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[7]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[8]]
