# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/board.xdc

# IP: ip/sign_multiplier/sign_multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sign_multiplier || ORIG_REF_NAME==sign_multiplier} -quiet] -quiet

# IP: ip/unsign_multiplier/unsign_multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==unsign_multiplier || ORIG_REF_NAME==unsign_multiplier} -quiet] -quiet
