# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VivadoProject/project_13/project_13.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/project_13/project_13.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProject/project_13/project_13.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Qtspim/exp13/ROM_B.coe
add_files D:/Qtspim/exp13/RAM_B.coe
read_verilog -library xil_defaultlib {
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/OP_Func.v
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/PC.v
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/REGS_ALU.v
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/CPU.v
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/ALU.v
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/Display.v
  D:/VivadoProject/project_13/project_13.srcs/sources_1/new/REGS.v
}
read_ip -quiet D:/VivadoProject/project_13/project_13.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/project_13/project_13.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet D:/VivadoProject/project_13/project_13.srcs/sources_1/ip/Inst_ROM/Inst_ROM.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/project_13/project_13.srcs/sources_1/ip/Inst_ROM/Inst_ROM_ooc.xdc]

read_ip -quiet D:/VivadoProject/project_13/project_13.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/project_13/project_13.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProject/project_13/project_13.srcs/constrs_1/new/board.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/project_13/project_13.srcs/constrs_1/new/board.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7a100tfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
