# 开启比特流压缩，优化 .bit 文件大小                                         
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]  
                                                               
set_property PULLDOWN true [get_ports input_data]                       
set_property IOSTANDARD LVCMOS18 [get_ports input_data]                 
set_property PACKAGE_PIN T3 [get_ports {input_data[0]}]                 
set_property PACKAGE_PIN U3 [get_ports {input_data[1]}]                 
set_property PACKAGE_PIN T4 [get_ports {input_data[2]}]                 
set_property PACKAGE_PIN V3 [get_ports {input_data[3]}]                 
set_property PACKAGE_PIN V4 [get_ports {input_data[4]}]                 
set_property PACKAGE_PIN W4 [get_ports {input_data[5]}]                 
set_property PACKAGE_PIN Y4 [get_ports {input_data[6]}]                 
set_property PACKAGE_PIN Y6 [get_ports {input_data[7]}]                 
set_property PACKAGE_PIN W7 [get_ports {input_data[8]}]                 
set_property PACKAGE_PIN Y8 [get_ports {input_data[9]}]                
set_property PACKAGE_PIN Y7 [get_ports {input_data[10]}]                
set_property PACKAGE_PIN T1 [get_ports {input_data[11]}]                
set_property PACKAGE_PIN U1 [get_ports {input_data[12]}]                
set_property PACKAGE_PIN U2 [get_ports {input_data[13]}]                
set_property PACKAGE_PIN W1 [get_ports {input_data[14]}]                
set_property PACKAGE_PIN W2 [get_ports {input_data[15]}]                
set_property PACKAGE_PIN Y1 [get_ports {input_data[16]}]                
set_property PACKAGE_PIN AA1 [get_ports {input_data[17]}]               
set_property PACKAGE_PIN V2 [get_ports {input_data[18]}]                
set_property PACKAGE_PIN Y2 [get_ports {input_data[19]}]                
set_property PACKAGE_PIN AB1 [get_ports {input_data[20]}]               
set_property PACKAGE_PIN AB2 [get_ports {input_data[21]}]               
set_property PACKAGE_PIN AB3 [get_ports {input_data[22]}]               
set_property PACKAGE_PIN AB5 [get_ports {input_data[23]}]               
set_property PACKAGE_PIN AA6 [get_ports {input_data[24]}]               
set_property PACKAGE_PIN R2 [get_ports {input_data[25]}]
set_property PACKAGE_PIN R3 [get_ports {input_data[26]}]
set_property PACKAGE_PIN T6 [get_ports {input_data[27]}]
set_property PACKAGE_PIN R6 [get_ports {input_data[28]}]
set_property PACKAGE_PIN U7 [get_ports {input_data[29]}]
set_property PACKAGE_PIN AB7 [get_ports {input_data[30]}]
set_property PACKAGE_PIN AB8 [get_ports {input_data[31]}]

set_property IOSTANDARD LVCMOS18 [get_ports key1]
set_property PACKAGE_PIN R4 [get_ports key1]
set_property IOSTANDARD LVCMOS18 [get_ports key2]
set_property PACKAGE_PIN AB6 [get_ports key2]
set_property IOSTANDARD LVCMOS18 [get_ports key3]
set_property PACKAGE_PIN V8 [get_ports key3]
set_property IOSTANDARD LVCMOS18 [get_ports key4]
set_property PACKAGE_PIN AA4 [get_ports key4]
set_property IOSTANDARD LVCMOS18 [get_ports key5]
set_property PACKAGE_PIN T5 [get_ports key5]
set_property IOSTANDARD LVCMOS18 [get_ports key6]
set_property PACKAGE_PIN AA8 [get_ports key6]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property PACKAGE_PIN V9 [get_ports rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports OF]
set_property PACKAGE_PIN R1 [get_ports OF]
set_property IOSTANDARD LVCMOS18 [get_ports ZF]
set_property PACKAGE_PIN P2 [get_ports ZF]

set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports which]
set_property PACKAGE_PIN N22 [get_ports {which[0]}]
set_property PACKAGE_PIN M21 [get_ports {which[1]}]
set_property PACKAGE_PIN M22 [get_ports {which[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN L21} [get_ports enable]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN H4} [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets key2_IBUF]   
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets key3_IBUF]   
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets key1_IBUF]   


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]   
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[1]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[2]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[3]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[4]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[5]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[6]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[7]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets swb_IBUF[8]]