# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Board.xdc

# IP: ip/div_gen_1/div_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_1 || ORIG_REF_NAME==div_gen_1} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet
