set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design] 

set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS18} [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0 5} [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports Inst_code]
set_property PACKAGE_PIN R1 [get_ports {Inst_code[31]}]
set_property PACKAGE_PIN P2 [get_ports {Inst_code[30]}]
set_property PACKAGE_PIN P1 [get_ports {Inst_code[29]}]
set_property PACKAGE_PIN N2 [get_ports {Inst_code[28]}]
set_property PACKAGE_PIN M1 [get_ports {Inst_code[27]}]
set_property PACKAGE_PIN M2 [get_ports {Inst_code[26]}]
set_property PACKAGE_PIN L1 [get_ports {Inst_code[25]}]
set_property PACKAGE_PIN J2 [get_ports {Inst_code[24]}]
set_property PACKAGE_PIN G1 [get_ports {Inst_code[23]}]
set_property PACKAGE_PIN E1 [get_ports {Inst_code[22]}]
set_property PACKAGE_PIN D2 [get_ports {Inst_code[21]}]
set_property PACKAGE_PIN A1 [get_ports {Inst_code[20]}]
set_property PACKAGE_PIN L3 [get_ports {Inst_code[19]}]
set_property PACKAGE_PIN G3 [get_ports {Inst_code[18]}]
set_property PACKAGE_PIN K4 [get_ports {Inst_code[17]}]
set_property PACKAGE_PIN G4 [get_ports {Inst_code[16]}]
set_property PACKAGE_PIN K1 [get_ports {Inst_code[15]}]
set_property PACKAGE_PIN J1 [get_ports {Inst_code[14]}]
set_property PACKAGE_PIN H2 [get_ports {Inst_code[13]}]
set_property PACKAGE_PIN G2 [get_ports {Inst_code[12]}]
set_property PACKAGE_PIN F1 [get_ports {Inst_code[11]}]
set_property PACKAGE_PIN E2 [get_ports {Inst_code[10]}]
set_property PACKAGE_PIN D1 [get_ports {Inst_code[9]}]
set_property PACKAGE_PIN B1 [get_ports {Inst_code[8]}]
set_property PACKAGE_PIN B2 [get_ports {Inst_code[7]}]
set_property PACKAGE_PIN N3 [get_ports {Inst_code[6]}]
set_property PACKAGE_PIN M3 [get_ports {Inst_code[5]}]
set_property PACKAGE_PIN K3 [get_ports {Inst_code[4]}]
set_property PACKAGE_PIN H3 [get_ports {Inst_code[3]}]
set_property PACKAGE_PIN N4 [get_ports {Inst_code[2]}]
set_property PACKAGE_PIN L4 [get_ports {Inst_code[1]}]
set_property PACKAGE_PIN J4 [get_ports {Inst_code[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports mclk]       
set_property PACKAGE_PIN R4 [get_ports mclk]    
set_property IOSTANDARD LVCMOS18 [get_ports rst]       
set_property PACKAGE_PIN AA4 [get_ports rst]


set_property IOSTANDARD LVCMOS18 [get_ports sw_ALU]       
set_property PACKAGE_PIN V8 [get_ports sw_ALU]
set_property IOSTANDARD LVCMOS18 [get_ports sw_ZFOF]       
set_property PACKAGE_PIN AA8 [get_ports sw_ZFOF]
set_property IOSTANDARD LVCMOS18 [get_ports sw_M_R]       
set_property PACKAGE_PIN V9 [get_ports sw_M_R]
set_property IOSTANDARD LVCMOS18 [get_ports sw_W_Data]       
set_property PACKAGE_PIN Y9 [get_ports sw_W_Data]


#ÊýÂë¹Ü
set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN H19 [get_ports {seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports which]
set_property PACKAGE_PIN N22 [get_ports {which[0]}]
set_property PACKAGE_PIN M21 [get_ports {which[1]}]
set_property PACKAGE_PIN M22 [get_ports {which[2]}]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN L21} [get_ports enable]


set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
     
