webtalk_init -webtalk_dir C:/Users/southernMD/vivado/project_10/project_10/project_10.sim/sim_1/behav/xsim/xsim.dir/Fetch_Inst_Code_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 22 17:25:02 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "25dc465d-a7b1-4e43-8b54-b6814b99d108" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f5045efc50244b459ac5a99cb1bfde7e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5560U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1120 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2210779593 -regid "" -xml C:/Users/southernMD/vivado/project_10/project_10/project_10.sim/sim_1/behav/xsim/xsim.dir/Fetch_Inst_Code_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/southernMD/vivado/project_10/project_10/project_10.sim/sim_1/behav/xsim/xsim.dir/Fetch_Inst_Code_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/southernMD/vivado/project_10/project_10/project_10.sim/sim_1/behav/xsim/xsim.dir/Fetch_Inst_Code_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
